---

homebrew_packages:
  - ansible
  - antibody
  - bat
  - git
  - httpie
  - jq
  - denisidoro/tools/navi
  - node
  - nvm
  - prettyping
  - python
  - thefuck
  - tldr
  - tree
  - yarn
  - zsh

# cask applications
