---

# homebrew applications
brew:
  - zsh
  - antibody
  - git
  - tldr
  - tree
  - bat
  - prettyping
  - httpie
  - node
  - yarn
  - nvm
  - python
  - denisidoro/tools/navi
  - ??

# cask applications
  - ??

# zsh antigen plugins
  - ?? add in zsh_plugins.txt?
  - or not... easier to pull from git and then let anisble run the packaging
